export interface PropertyInventoryItem {
  id: string;
  address: string;
  parcelKey: string;
  businessName?: string;
  buildingName?: string;
  tier: "1A" | "1B" | "2" | "3";
  status: "Occupied" | "Vacant" | "Under Renovation" | "In Pipeline";
  squareFeet: number;
  priorFoodUse: boolean;
  kitchenInPlace: boolean;
  hoodAndVent: boolean;
  greaseInterceptor: boolean;
  seatingCapacity: number;
  askingRent?: string;
  ownerName: string;
  ownerAppetiteTI: "High" | "Moderate" | "Low" | "Unknown";
  conflictFlag: boolean;
  notes: string;
  surveyDate: string;
}

export const CORRIDOR_METRICS = {
  assessableParcels: 126,
  assessableValue: "$45.9M",
  commercialSquareFeet: "732,814 SF",
  vacantParcelsCount: 10,
  foodEstablishmentsCurrent: 14,
  corridorCorePopulation: 8027,
  households: 3836,
  noVehiclePct: "27.6%",
  householdsAbove75k: "22.7%",
  daytimeAnchorsServed: "4,000+ annual program visitors",
};

export const INVENTORY_DATA: PropertyInventoryItem[] = [
  {
    id: "PROP-01",
    address: "3338 N. Dr. MLK Jr. Drive",
    parcelKey: "2820542000",
    businessName: "Former Sam's Place Jazz Café",
    buildingName: "Sam's Place Building",
    tier: "1B",
    status: "Vacant",
    squareFeet: 2450,
    priorFoodUse: true,
    kitchenInPlace: true,
    hoodAndVent: true,
    greaseInterceptor: true,
    seatingCapacity: 64,
    askingRent: "$16.50/SF NNN",
    ownerName: "Community Preservation Partners LLC",
    ownerAppetiteTI: "Moderate",
    conflictFlag: false,
    notes: "Prime Tier 1B anchor candidate. Infrastructure in place; ideal for immediate reactivation or incubator front-end.",
    surveyDate: "2026-08-12",
  },
  {
    id: "PROP-02",
    address: "2215 N. Dr. MLK Jr. Drive",
    parcelKey: "3220819000",
    businessName: "Former Pepperpot",
    buildingName: "Pepperpot Building",
    tier: "1B",
    status: "Vacant",
    squareFeet: 3750,
    priorFoodUse: true,
    kitchenInPlace: true,
    hoodAndVent: true,
    greaseInterceptor: true,
    seatingCapacity: 99,
    askingRent: "$18.00/SF Modified Gross",
    ownerName: "Private Owner-Occupant Estate",
    ownerAppetiteTI: "Low",
    conflictFlag: false,
    notes: "Turnkey full-service footprint with high-volume dining area and second kitchen prep space.",
    surveyDate: "2026-08-14",
  },
  {
    id: "PROP-03",
    address: "2323 N. Dr. MLK Jr. Drive",
    parcelKey: "3221224112",
    businessName: "Pete's Fruit Market & Surplus Parcel",
    buildingName: "North & MLK Commercial Center",
    tier: "1A",
    status: "Occupied",
    squareFeet: 16505,
    priorFoodUse: true,
    kitchenInPlace: false,
    hoodAndVent: false,
    greaseInterceptor: true,
    seatingCapacity: 0,
    askingRent: "Ground Lease / Partnership",
    ownerName: "SH Acquisition LLC (RACM / City Vehicle)",
    ownerAppetiteTI: "High",
    conflictFlag: false,
    notes: "Primary candidate lot for the multi-vendor Food Truck Park and shared outdoor hospitality node.",
    surveyDate: "2026-08-10",
  },
  {
    id: "PROP-04",
    address: "1835-1839 N. Dr. MLK Jr. Drive",
    parcelKey: "3540103000",
    businessName: "One Seven Cafe & Lounge (Filing)",
    buildingName: "Historic Commercial Block",
    tier: "1A",
    status: "Under Renovation",
    squareFeet: 3100,
    priorFoodUse: true,
    kitchenInPlace: true,
    hoodAndVent: true,
    greaseInterceptor: true,
    seatingCapacity: 75,
    askingRent: "Leased",
    ownerName: "Bronzeville Commercial Realty",
    ownerAppetiteTI: "High",
    conflictFlag: false,
    notes: "Successful backfill of former Mi Casa Su space; active tenant fit-out underway.",
    surveyDate: "2026-08-18",
  },
  {
    id: "PROP-05",
    address: "2150 N. Dr. MLK Jr. Drive",
    parcelKey: "3220412000",
    businessName: "ThriveOn King Ground Commercial",
    buildingName: "ThriveOn King (GMF / MCW)",
    tier: "1A",
    status: "Occupied",
    squareFeet: 12000,
    priorFoodUse: true,
    kitchenInPlace: true,
    hoodAndVent: true,
    greaseInterceptor: true,
    seatingCapacity: 120,
    askingRent: "Program / Co-op",
    ownerName: "ThriveOn King Development",
    ownerAppetiteTI: "High",
    conflictFlag: false,
    notes: "Anchor civic presence; daytime demand engine for morning and lunch trade.",
    surveyDate: "2026-07-29",
  },
  {
    id: "PROP-06",
    address: "2418 N. Dr. MLK Jr. Drive",
    parcelKey: "3220911000",
    businessName: "Victory Lofts Ground Commercial",
    buildingName: "Victory Lofts (2028 Delivery)",
    tier: "2",
    status: "In Pipeline",
    squareFeet: 7500,
    priorFoodUse: false,
    kitchenInPlace: false,
    hoodAndVent: false,
    greaseInterceptor: false,
    seatingCapacity: 80,
    askingRent: "Subject to Underwriting",
    ownerName: "KG Development / FIT Investment Group",
    ownerAppetiteTI: "High",
    conflictFlag: true,
    notes: "Scheduled 7,500 SF cultural hub with commercial production kitchen. Tenanting decisions set for Year 1 (2027).",
    surveyDate: "2026-08-01",
  },
  {
    id: "PROP-07",
    address: "2601 N. Dr. MLK Jr. Drive",
    parcelKey: "3120114000",
    businessName: "Commercial Storefront",
    buildingName: "Harambee Corner Building",
    tier: "2",
    status: "Vacant",
    squareFeet: 1850,
    priorFoodUse: false,
    kitchenInPlace: false,
    hoodAndVent: false,
    greaseInterceptor: false,
    seatingCapacity: 45,
    askingRent: "$14.00/SF NNN",
    ownerName: "Northside Urban Properties",
    ownerAppetiteTI: "Moderate",
    conflictFlag: false,
    notes: "Clean white box; prime candidate for Tier 2 kitchen package grant match.",
    surveyDate: "2026-08-05",
  },
  {
    id: "PROP-08",
    address: "2912 N. Dr. MLK Jr. Drive",
    parcelKey: "3120618000",
    businessName: "Historic Corner Retail",
    buildingName: "Legacy Commercial Block",
    tier: "3",
    status: "Vacant",
    squareFeet: 4200,
    priorFoodUse: false,
    kitchenInPlace: false,
    hoodAndVent: false,
    greaseInterceptor: false,
    seatingCapacity: 0,
    askingRent: "Requires Redevelopment",
    ownerName: "Out-of-State Trust",
    ownerAppetiteTI: "Low",
    conflictFlag: false,
    notes: "Requires complete structural and roof repair prior to food and beverage utility installation.",
    surveyDate: "2026-07-22",
  },
];

export const MODULES_SPEC = [
  {
    id: "M01",
    name: "Master Parcel & Storefront Inventory",
    target: "126 assessable parcels + all commercial storefronts",
    outcome: "Unified single source of truth for physical status, commercial square footage, historical operations, and parcel ties.",
    status: "Ready for Core Build",
    priority: "P0 · Phase 1",
  },
  {
    id: "M02",
    name: "Mobile Storefront Survey & Field Audit",
    target: "Student practicum & staff field survey",
    outcome: "Standardized questionnaire for hood, grease, accessibility, seating, photos, and quality-control manager approval queue.",
    status: "Ready for Core Build",
    priority: "P0 · Phase 1",
  },
  {
    id: "M03",
    name: "Space Readiness Tiers & Activation Pipeline",
    target: "Tiers 1A, 1B, 2, and 3 taxonomy",
    outcome: "Directs appropriate intervention (retention, fast-fill, kitchen capital, or redevelopment) rather than treating all vacancies alike.",
    status: "Ready for Core Build",
    priority: "P0 · Phase 1",
  },
  {
    id: "M04",
    name: "Owner, Developer & Institutional Engagement",
    target: "Key owners, RACM, GMF, YWCA, hospitals",
    outcome: "Tracks tenant-improvement appetite, lease flexibility, institutional catering demand, and time-sensitive 2027 tenanting decisions.",
    status: "Design Completed",
    priority: "P1 · Phase 1-2",
  },
  {
    id: "M05",
    name: "Deal Book & Recruitment Portal",
    target: "Multi-unit operators & regional chefs",
    outcome: "Curated, exportable marketing packages for Tier 1B and Tier 2 spaces with verified dimensions, utilities, and incentive stacks.",
    status: "Design Completed",
    priority: "P1 · Phase 2",
  },
  {
    id: "M06",
    name: "Existing-Operator Retention & Margin Workspace",
    target: "Corridor F&B operators currently open",
    outcome: "Confidential benchmarking, operations consulting, menu pricing, delivery platform margins, and stabilization grants.",
    status: "Design Completed",
    priority: "P1 · Phase 2",
  },
  {
    id: "M07",
    name: "Mentor–Protégé Structured Program",
    target: "Proven operators paired with new talent",
    outcome: "4 structured operating models (equity, licensing, 2nd location, shared services) paired before lease signing to ensure local wealth retention.",
    status: "Design Completed",
    priority: "P1 · Phase 2",
  },
  {
    id: "M08",
    name: "Food Truck Park & Pop-Up Incubator",
    target: "2323 N MLK candidate parcel & Tier 1B spaces",
    outcome: "Feeder system providing low-risk concept testing, evening foot-traffic critical mass, and winter-resilient structures.",
    status: "Design Completed",
    priority: "P1 · Phase 3",
  },
  {
    id: "M09",
    name: "Trade Area & Demographic Intelligence",
    target: "ACS 5-yr, LEHD OnTheMap, and Mobility data",
    outcome: "Surfaces the bimodal corridor income reality ($19.8K west vs $64.8K east) to defend multi-price-point offerings.",
    status: "Design Completed",
    priority: "P2 · Phase 3",
  },
  {
    id: "M10",
    name: "Incentive Stacking & Capital Underwriting",
    target: "City, State, GMF, Bader, & BID match",
    outcome: "Underwrites Tier 2 kitchen equipment pools ($25k+), storefront activation, white-box grants, and destination-restaurant predevelopment.",
    status: "Design Completed",
    priority: "P1 · Phase 2",
  },
  {
    id: "M11",
    name: "Public Body Governance & Conflict Registry",
    target: "BID Board of Directors & RACM links",
    outcome: "Enforces mandatory affiliation flags, recusal workflows, and Wisconsin Open Meetings compliance across all property decisions.",
    status: "Governance Defined",
    priority: "P0 · Phase 1",
  },
  {
    id: "M12",
    name: "Annual Evaluation & Anti-Displacement Metrics",
    target: "Board, Greater Milwaukee Foundation, Bader",
    outcome: "Reports net change among pre-program businesses, Tier 2-to-1 conversions, protégé graduations, and assessment sustainability.",
    status: "Metrics Defined",
    priority: "P0 · Phase 1",
  },
];
